src/employee_management/people/routes.py
from employee_management import app, db
#
from employee_management.people.forms import RegistrationForm, LoginForm, EditProfileForm
#
from flask import Blueprint
from flask import render_template, flash, redirect, url_for
from flask import request
#
from flask_login import login_user, current_user, logout_user, login_required
#
from employee_management.models import Person
#
import os
import secrets
from PIL import Image
#
from datetime import datetime, timedelta

#=============================================================================================================================
people_domain = Blueprint('people_domain', __name__)    
#=============================================================================================================================
@people_domain.route("/register", methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        #
        person = Person(name=form.name.data,email=form.email.data,username=form.username.data,password=form.password.data)
        db.session.add(person)
        db.session.commit()
        #
        flash("Account created for "+str(form.username.data)+"!", 'success')
        #
        return redirect(url_for('people_domain.login'))
    
    return render_template('register.html', title='Register', form=form)

@people_domain.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = Person.query.filter_by(username=form.username.data).first()
        if user and user.password==form.password.data:
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@people_domain.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('home'))
#=============================================================================================================================
@people_domain.route("/profile",methods=['GET','POST'])
@login_required
def profile():    
    person_id = int(request.args.get('person_id',-1))
    if person_id == -1:
        flash("Could not find the requested profile","danger")
        return redirect(url_for('home'))
    #
    user = Person.query.filter_by(id=person_id).first()
    #
    form = EditProfileForm()
    if form.validate_on_submit():
        #
        if form.picture.data:
            picture_file = save_picture(request.files[form.picture.name])
            current_user.image_file = picture_file
        current_user.name = form.name.data
        current_user.email = form.email.data
        db.session.commit()
        #
        flash("Profile adjusted for "+current_user.name+"!", 'success')
    #
    form.name.data = current_user.name
    form.email.data = current_user.email
    #
    posts = user.posts
    posts.sort(key= lambda p:p.date)
    posts.reverse()
    #
    image_file = url_for('static', filename='profile_pics/' + user.image_file)
    #
    colleagues = set()
    if len(user.employments)!=0:
        for employement in user.employments:
            for personnel_data in employement.project.personnel:
                if personnel_data.person.id != user.id:
                    colleagues.add(personnel_data.person)
        colleagues = list(colleagues)
        colleagues.sort(key=lambda c:c.name)
    #
    person_projects = None
    day_data_list = None
    if len(posts)!=0:
        #
        today = datetime.now()
        day_data = dict()
        for i in range(30):
            day = today - timedelta(days=i)
            #
            key = day.strftime("%d.%m.%Y")
            #
            day_data[key] = dict()
            day_data[key]['hours'] = sum([post.duration for post in posts if post.date.date()==day.date()])
            day_data[key]['posts'] = sum([1 for post in posts if post.date.date()==day.date()])
            #
        day_data_list = []
        for day_id in day_data:
            day_data_list.append((day_id,day_data[day_id]['hours'],day_data[day_id]['posts']))
        day_data_list.reverse()    
        #
        person_projects = []
        for employement in user.employments:
            if employement.role.name=='worker':
                user_hours = sum([post.duration for post in user.posts if post.project_id==employement.project_id])
                user_posts = sum([1 for post in user.posts if post.project_id==employement.project_id])
                person_projects.append((employement.project.name,user_hours,user_posts))
    #
    if person_projects is None and day_data_list is None:
        if len(colleagues)!=0:
            return render_template('profile.html',title='Profile',user=user, image_file=image_file, form=form, posts=posts, colleagues=colleagues)
        else:
            return render_template('profile.html',title='Profile',user=user, image_file=image_file, form=form, posts=posts)
    else:
        if len(colleagues)!=0:
            return render_template('profile.html',title='Profile',user=user, image_file=image_file, form=form, posts=posts, person_projects=person_projects, day_data=day_data_list, colleagues=colleagues)
        else:
            return render_template('profile.html',title='Profile',user=user, image_file=image_file, form=form, posts=posts, person_projects=person_projects, day_data=day_data_list)
    
def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(app.root_path, 'static/profile_pics', picture_fn)

    output_size = (125, 125)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)

    return picture_fn

src/employee_management/posts/routes.py
from employee_management import db
#
from employee_management.posts.forms import EditPostForm
#
from flask import Blueprint
from flask import render_template, flash, redirect, url_for
from flask import request
#
from flask_login import current_user, login_required
#
from employee_management.models import Post
    
#=============================================================================================================================
posts_domain = Blueprint('posts_domain', __name__)    
#=============================================================================================================================
@posts_domain.route("/delete_post", methods=['POST'])
@login_required
def delete_post():
    post_id = int(request.form.get('post_id', -1))
    posts_which_can_be_deleted = set([post.id for post in current_user.posts])
    #
    if post_id != -1 and post_id in posts_which_can_be_deleted:
        Post.query.filter_by(id=post_id).delete()
        db.session.commit()
        #
        flash("Post deleted!", 'success')     
    #
    return redirect(url_for('people_domain.profile',person_id=current_user.id))

@posts_domain.route("/edit_post", methods=['GET', 'POST'])
@login_required
def edit_post():
    post_id = int(request.args.get('post_id', -1))
    posts_which_can_be_edited = set([post.id for post in current_user.posts])
    if post_id != -1 and post_id in posts_which_can_be_edited:
        post = Post.query.filter_by(id=post_id).first()
        #
        form = EditPostForm()
        #
        if form.validate_on_submit():
            post_text = form.content.data
            post_duration = int(form.duration.data if form.duration.data is not None else 0)
            #
            post.content = post_text
            post.duration = post_duration
            db.session.commit()
            #
            flash("Post edited successfully!", 'success') 
        #
        form.content.data = post.content
        form.duration.data = post.duration
        #            
        return render_template('post.html',title='Post',form=form)
    #
    flash("Post could not be found!", 'danger') 
    return redirect(url_for('home'))
#=============================================================================================================================

src/employee_management/projects/routes.py
from employee_management import app, db
#
from employee_management.projects.forms import CreateProjectForm, EditProjectForm
from employee_management.projects.reports import generate_report
#
from flask import Blueprint
from flask import render_template, flash, redirect, url_for, send_file
from flask import request
#
from flask_login import current_user, login_required
#
from employee_management.models import Employment, Project, Person, Role
#
import os
from datetime import datetime, timedelta
    
#=============================================================================================================================
projects_domain = Blueprint('projects_domain', __name__)        
#=============================================================================================================================

@projects_domain.route("/projects", methods=['GET', 'POST'])
@login_required
def projects():    
    #Check for mistakes
    create_project_form = CreateProjectForm()
    if create_project_form.validate_on_submit():
        #
        project_name = str(create_project_form.name.data)
        #
        project = Project(name=project_name)
        manager_role = Role.query.filter_by(name='manager').first()
        employment = Employment(person=current_user, project=project, role=manager_role)
        db.session.add(project)
        db.session.add(employment)
        db.session.commit()
        #
        flash("Project "+project_name+" created successfully!", 'success')     

    #Get all people 
    people = Person.query.all()

    #Get all the projects of the current user
    projects = [employment.project for employment in current_user.employments if employment.role.name=="manager"]    
    for project in projects:
        project.time = sum([post.duration for post in project.posts])
        project_people = [person for person in people if person.id not in set([p.person_id for p in project.personnel if p.role.name=='worker'])]
        project_potential_managers = [person for person in people if person.id not in set([p.person_id for p in project.personnel if p.role.name=='manager'])]
        if len(project_people)>0:
            project.people = project_people
            project.managers = project_potential_managers
    
    #    
    return render_template('projects.html', title='Projects', projects=projects, people=people, create_project_form=create_project_form)


@projects_domain.route("/project", methods=['GET'])
@login_required
def project():    
    project_id = int(request.args.get('project_id', -1))
    if project_id == -1:
        flash("Project could not be found",'danger')
        return redirect(url_for('home'))
    #    
    project = Project.query.filter_by(id=project_id).first()
    #
    for person in project.personnel:
        if person.role.name=='worker':
            person.total_hours = sum([post.duration for post in project.posts if post.person_id==person.person.id])
            person.total_posts = sum([1 for post in project.posts if post.person_id==person.person.id])
    #
    day_data_list = []
    if len(project.posts)>0:    
        today = datetime.now()
        day_data = dict()
        for i in range(30):
            day = today - timedelta(days=i)
            #
            key = day.strftime("%d.%m.%Y")
            #
            day_data[key] = dict()
            day_data[key]['hours'] = sum([post.duration for post in project.posts if post.date.date()==day.date()])
            day_data[key]['posts'] = sum([1 for post in project.posts if post.date.date()==day.date()])
            #
        for day_id in day_data:
            day_data_list.append((day_id,day_data[day_id]['hours'],day_data[day_id]['posts']))
        day_data_list.reverse()
    #
    posts = project.posts
    posts.sort(key=lambda p:p.date)
    posts.reverse()
    #
    if len(day_data_list)!=0:
        return render_template('project_details.html', title='Project', project=project, posts=posts, day_data=day_data_list)
    else:
        return render_template('project_details.html', title='Project', project=project, posts=posts)

@projects_domain.route("/edit_project", methods=['GET','POST'])
@login_required
def edit_project():
    project_id = int(request.args.get('project_id'))
    if project_id is not None:
        project = Project.query.filter_by(id=project_id).first()
        #
        edit_project_form = EditProjectForm()
        if edit_project_form.validate_on_submit():
            #
            project_name = str(edit_project_form.name.data)
            if project is not None:
                project.name = project_name
                db.session.commit()
                #
                flash("Project "+project_name+" updated successfully!", 'success')     
        #
        edit_project_form.name.data = project.name
        #    
        return render_template('edit_project.html', title='Project', form = edit_project_form, project=project)
    else:
        flash("Project could not be found",'danger')
        return redirect(url_for('home'))

@projects_domain.route("/add_worker_to_project", methods=['POST'])
@login_required
def add_worker_to_project():
    project_id = int(request.form.get('project_id', -1))
    person_id = int(request.form.get('employee_id', -1))
    #
    if project_id != -1 and person_id != -1:
        worker_role = Role.query.filter_by(name='worker').first()
        employment = Employment(person_id=person_id, project_id=project_id, role=worker_role)
        db.session.add(employment)
        db.session.commit()
    #
    flash("Worker added to project!", 'success')     
    #
    return redirect(url_for('projects_domain.projects'))

@projects_domain.route("/remove_worker_from_project", methods=['POST'])
@login_required
def remove_worker_from_project():
    project_id = int(request.form.get('project_id', -1))
    person_id = int(request.form.get('person_id', -1))
    #
    if project_id != -1 and person_id != -1:
        worker_role = Role.query.filter_by(name='worker').first()
        Employment.query.filter_by(project_id=project_id ).filter_by(person_id=person_id).filter_by(role_id=worker_role.id).delete()
        db.session.commit()
    #
    flash("Worker removed from project!", 'success')     
    #
    return redirect(url_for('projects_domain.projects'))
    

@projects_domain.route("/add_manager_to_project", methods=['POST'])
@login_required
def add_manager_to_project():
    project_id = int(request.form.get('project_id', -1))
    manager_id = int(request.form.get('manager_id', -1))
    #
    if project_id != -1 and manager_id != -1:
        worker_role = Role.query.filter_by(name='manager').first()
        employment = Employment(person_id=manager_id, project_id=project_id, role=worker_role)
        db.session.add(employment)
        db.session.commit()
    #
    flash("Manager added to project!", 'success')     
    #
    return redirect(url_for('projects_domain.projects'))


@projects_domain.route("/remove_manager_from_project", methods=['POST'])
@login_required
def remove_manager_from_project():
    project_id = int(request.form.get('project_id', -1))
    person_id = int(request.form.get('person_id', -1))
    #
    if project_id != -1 and person_id != -1:
        worker_role = Role.query.filter_by(name='manager').first()
        Employment.query.filter_by(project_id=project_id ).filter_by(person_id=person_id).filter_by(role_id=worker_role.id).delete()
        db.session.commit()
    #
    flash("Manager removed from project!", 'success')     
    #
    return redirect(url_for('projects_domain.projects'))


@projects_domain.route("/delete_project", methods=['POST'])
@login_required
def delete_project():
    project_id = int(request.form.get('project_id', -1))
    #
    if project_id != -1:
        Project.query.filter_by(id=project_id).delete()
        db.session.commit()
        #
        flash("Project deleted!", 'success')     
    #
    return redirect(url_for('projects_domain.projects'))
#=============================================================================================================================

@projects_domain.route("/generate_project_report", methods=['POST'])
@login_required
def generate_project_report():
    project_id = int(request.form.get('project_id', -1))
    if project_id == -1:
        flash("Project could not be found",'danger')
        return redirect(url_for('home'))
    #    
    project = Project.query.filter_by(id=project_id).first()
    #
    report_folder = os.path.join(app.root_path, 'static/reports')
    image_folder = os.path.join(app.root_path, 'static/profile_pics')
    report_location = generate_report(report_folder, project.name, project.name, project.posts, image_folder)
    #
    return send_file(report_location, as_attachment=True)

src/employee_management/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <legend class="about-title">About us</legend>
        </div>
        <!-- -->
        <p>
            Employee management turns project progress reporting into a social media experience.
            <br/>
            The aim is to simplify communication between project managers and project participants, while making sure all communication is saved and ready for analysis.
            <br/>
            Additionally it offeres functionality to track project time investmenets. 
        </p>
      </div>
    </article>
    <div class="border-top pt-3">
        <small class="text-muted">
            Do you wish to customize your experience? <a class="ml-2" href="{{ url_for('contact') }}">Contact us</a>
        </small>
    </div>
{% endblock content %}

src/employee_management/templates/home.html
{% extends "layout.html" %}
{% block head %}
    <!-- Socket support -->

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    <script>
        function generate_post_html(data){
            var article = '<article class="media content-section"><img class="rounded-circle article-img" src="' 
                          + data.image_file+ 
                          '"><div class="media-body"><div class="article-metadata"><a class="mr-2" href="#"> ' 
                          + data.person_name + 
                          '</a><small class="text-muted">' 
                          + data.date + 
                          '</small></div><h2><a class="article-title" href="#">' 
                          + data.project_name + 
                          '</a></h2><p class="article-content">' 
                          + data.content + 
                          '</p>';
            if(data.duration>0){
                article += '<p class="article-content"> <i> Duration: ' + data.duration + ' h </i></p>';
            }   
            article += '</div></article>';
            return article;        
        }    
    </script>
    
    <script>
    
           var last_post_date = '{{ last_post_date }}';
    
           //Had to do this dynamic jquery load because jQuery seems to be overwritten by something
           run_jquery = function(request_to_run) {
                // Load the script
                var script = document.createElement("SCRIPT");
                script.src = 'https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js';
                script.type = 'text/javascript';
                script.onload = request_to_run;
                document.getElementsByTagName("head")[0].appendChild(script);
            };    
            
    
            $(document).ready(function(){
                $("#more-posts-button").click(function(){
                    run_jquery(function() {
                        var $ = window.jQuery;
                        $.post( "get_older_posts", {last_date: last_post_date} ,function( response_data ) {
                            var post_holder  = document.getElementById("posts-holder");
                            if (post_holder){
                                var html = '';
                                for(var i=0; i< response_data.posts.length; i++){
                                    post_data = response_data.posts[i];
                                    html += generate_post_html(post_data);                         
                                }
                                post_holder.innerHTML = post_holder.innerHTML + html;
                            }
                            //
                            last_post_date = response_data.last_post_date;
                            //
                            if(!response_data.more_posts){
                                var load_more_btn = document.getElementById("more-posts-button");
                                if(load_more_btn){
                                    load_more_btn.hidden = true;
                                }
                            }
                        });
                    });
                });
            });  
    </script>
    
    <script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js" integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
    <script>
        var socket = io();
        //
        var global_data;
        socket.on( 'new_post', function( data ) {
          console.log(data);
          global_data = data;
          //
          var post_holder  = document.getElementById("posts-holder");
          if (post_holder){
              var article = generate_post_html(data);
              post_holder.innerHTML = article + post_holder.innerHTML;
          }
           
        })
    </script>
{% endblock head %}

{% block content %}
    <!-- Post form -->
    {% if is_worker %}
    <div class="content-section">
        <form method="POST" action="">
            {{ post_form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Notify your manager</legend>
                <div class="form-group">
                    {{ post_form.content.label(class="form-control-label") }}
                    {% if post_form.content.errors %}
                        {{ post_form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in post_form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ post_form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ post_form.project.label(class="form-control-label") }}
                    {% if post_form.project.errors %}
                        {{ post_form.project(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in post_form.project.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ post_form.project(class="form-control") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ post_form.duration.label(class="form-control-label") }}
                    {% if post_form.duration.errors %}
                        {{ post_form.duration(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in post_form.duration.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ post_form.duration(class="form-control") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group text-right">
                {{ post_form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    {% endif %}
    <!-- Posts -->
    {% if is_manager %}
        <div id="posts-holder" class="posts-holder">
        {% for post in posts %}
            <article class="media content-section">
              <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"> 
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="{{url_for('people_domain.profile',person_id=post.author.id)}}">{{ post.author.name }}</a>
                  <small class="text-muted">{{ post.date.strftime("%d.%m.%Y %H:%M") }}</small>
                </div>
                <h2><a class="article-title" href="{{url_for('projects_domain.project',project_id=post.project.id)}}">{{ post.project.name }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
                {% if post.duration > 0 %}
                    <p class="article-content"> <i> Duration: {{ post.duration }} h </i></p>
                {% endif%}
              </div>
            </article>
        {% endfor %}
        </div>
        
        {% if more_posts %}
            <button class="btn btn-block btn-outline-info" id="more-posts-button" >Load more posts</button>
            <br/>
        {% endif %}
        
    {% endif %}
{% endblock content %}

src/employee_management/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% block head %}{% endblock %}

    <!-- Custom title management -->
    {% if title %}
        <title>EM-{{ title }}</title>
    {% endif %}
    
    <!-- block to add charts if needed -->    
    {% block chart %}{% endblock %}
    
    
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
          <a class="navbar-brand mr-4" href="{{ url_for('home')}}">EM</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              {% if current_user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('home')}}">Home <span class="sr-only">(current)</span></a>
                  </li>
              {% endif %}
            </ul>
          </div>
          <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('people_domain.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('people_domain.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('people_domain.register') }}">Register</a>
              {% endif %}
            </div>          
        </nav>      
    </header>
    
    <main class="container">
      <div class="row">
        <div class="col-md-8" style="padding-top:5rem;">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}        
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
        <div class="sticky-top" style="padding-top:5rem;">
              {% if current_user.is_authenticated %}
                      <div class="content-section">
                        <h3>Administer</h3>
                        <p class="text-muted"> 
                          <ul class="list-group">
                            <li class="list-group-item list-group-item-light"><a href="{{ url_for('people_domain.profile',person_id=current_user.id) }}">Profile - {{ current_user.name }}</a></li>
                            <li class="list-group-item list-group-item-light"><a href="{{ url_for('projects_domain.projects') }}">Projects</a></li>
                          </ul>
                        </p>
                      </div>
                {% endif %}
                  <div class="content-section">
                    <h3>Help</h3>
                    <p class="text-muted"> 
                      <ul class="list-group">
                        <li class="list-group-item list-group-item-light"><a href="{{ url_for('about') }}">About us</a></li>
                        <li class="list-group-item list-group-item-light"><a href="{{ url_for('contact') }}">Contact us</a></li>
                      </ul>
                    </p>
                  </div>
            </div>          
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>